# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy and Pandas libraries provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built in arithmatic functions.  In this lab we shall calculate and compare the processing speed required for calculating a dot product both using basic arithmatic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:
* Compare the performance of high dimensional matrix operations in Numpy vs. pure Python

## Problem
> **Write a routine to calculate the dot product between two 200 x 200 dimensional matrices using:**

> **a) Pure Python**

> **b) Numpy's `.dot()`**


### Create two 200 x 200 matrices in Python and fill them with random values using `np.random.rand()` 

In [19]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

# Set up the variables
A = np.zeros((200,200), dtype=int)
B = np.zeros((200,200), dtype=int)



for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        A[i,j] = np.random.randint(10)
        B[i,j] = np.random.randint(10)
        
C = np.zeros((A.shape[0], B.shape[1]), dtype=int)

print(A, '\n')
print(B)

[[7 7 2 ... 9 0 1]
 [6 7 9 ... 3 6 9]
 [1 5 9 ... 6 8 7]
 ...
 [0 6 0 ... 7 4 8]
 [9 9 5 ... 5 5 2]
 [6 1 1 ... 4 6 5]] 

[[5 8 4 ... 9 5 3]
 [1 4 4 ... 1 7 8]
 [2 5 6 ... 0 8 1]
 ...
 [2 2 5 ... 9 6 6]
 [9 4 8 ... 5 1 6]
 [4 4 3 ... 6 7 6]]


In [20]:
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(C.shape[1]):
            C[i,j] += A[i,k]*B[k,j]
            
print(C)

[[3774 4143 4145 ... 4136 4339 3628]
 [4145 4328 4214 ... 4380 4394 4092]
 [4273 4095 4023 ... 4324 4328 3954]
 ...
 [3861 3801 3760 ... 3762 3968 3663]
 [4282 4500 4342 ... 4557 4581 4024]
 [4040 4017 3878 ... 4211 4006 3682]]


In [21]:
A.dot(B)

array([[3774, 4143, 4145, ..., 4136, 4339, 3628],
       [4145, 4328, 4214, ..., 4380, 4394, 4092],
       [4273, 4095, 4023, ..., 4324, 4328, 3954],
       ...,
       [3861, 3801, 3760, ..., 3762, 3968, 3663],
       [4282, 4500, 4342, ..., 4557, 4581, 4024],
       [4040, 4017, 3878, ..., 4211, 4006, 3682]])

### Pure Python

* Initialize an zeros filled numpy matrix with necessary rows and columns for storing result. 
* In Python Calculate the dot product using the formula 
![](formula.png)
* Use Python's `timeit` library to calculate the processing time. 
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an indepth explanation on how to time a function or routine in python. 

**Hint**: Use nested for loop for accessing, calculating and storing each scalar value in the result matrix.

In [22]:
import timeit

# Start the timer
start = timeit.default_timer()

# Matrix multiplication in pure Python
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(C.shape[1]):
            C[i,j] += A[i,k]*B[k,j]

time_spent = timeit.default_timer() - start


print('Pure Python Time:', time_spent, 'sec.')

Pure Python Time: 11.957569613772193 sec.


## Numpy 
Set the timer and calculate the time taken by `.dot()` function for multiplying A and B 


In [23]:
# start the timer
start = timeit.default_timer()

# Matrix multiplication in numpy
A.dot(B)

time_spent = timeit.default_timer() - start
print('Numpy Time:', time_spent, 'sec.')

Numpy Time: 0.00892720282308801 sec.


### Your comments 

Way way way way faster using the built-in numpy method

## Summary

In this lab, we performed a quick comparison between calculating a dot product in numpy vs python built in function. We saw that Numpy is computationally much more efficient that Python code due to highly sophisticated implementation of Numpy source code. You are encouraged to always perform such tests to fully appreciate the use of an additional library in Python. 